---
# tasks file for ansible-role-resolver

- name: Append supersede domain-name-servers to /etc/dhclient.conf
  lineinfile:
    dest: /etc/dhclient.conf
    regexp: "^supersede\\s+domain-name-servers\\s+(?!{{ resolver_nameservers | predictable_shuffle(ansible_fqdn) | join(',') }});"
    state: absent
  when: "{{ resolver_dhclient_enabled }}"

- name: Append supersede domain-name-servers to /etc/dhclient.conf
  lineinfile:
    dest: /etc/dhclient.conf
    line: "supersede domain-name-servers {{ resolver_nameservers | predictable_shuffle(ansible_fqdn) | join(',') }};"
  register: register_dhclient_conf
  when: "{{ resolver_dhclient_enabled }}"

- name: Restart dhclient
  service:
    name: dhclient
    state: restarted
    arguments: "{{ resolver_dhclient_interface }}"
  when: register_dhclient_conf.changed

- name: Create resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  when: "{{ not resolver_dhclient_enabled }}"

- name: Create resolvconf.conf
  template:
    src: resolvconf.conf.j2
    dest: /etc/resolvconf.conf
  when: "{{ resolver_dhclient_enabled }}"
  notify: Update resolv.conf
